project:
  type: website
  output-dir: docs

website:
  title: "Michael Gao"
  description: "Notes on mechanistic interpretability"
  site-url: https://induction1.github.io
  draft-mode: unlinked
  navbar:
    left:
      - text: "Notes"
        href: notes.qmd
      - text: "Research"
        href: research.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Induction1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



